### PR TITLE
Update icon.svg

### PR DESCRIPTION
**Pull request by adambelis**
new icon

### CODE REVIEW

**Comment by Ev1lbl0w** [comment]
Before merging, did you use the original icon shape (either from the [original logo](https://github.com/Ev1lbl0w/controller_icons/blob/master/icon.svg) or from [here](https://www.svgrepo.com/svg/255536/game-controller-gamepad)), or from another source? If it was another source, please provide the original source so I can credit the original work too.

**Comment by adambelis** [comment]
I created this from the scratch so its 100% my contribution . I am only outor of this icon

**Comment by Ev1lbl0w** [comment]
> I created this from the scratch so its 100% my contribution. I am only autor of this icon . forgot to add licensing . its a public domain cc0

Thanks. I'll create a pull request shortly to credit your work, let me know if there's any issues on how I present this information.

**Comment by adambelis** [comment]
honestly i dont care :D if you want you can credit me by name

**Pull request merged**
